"""Initial event analytics pipeline schema.

Revision ID: c92d68dd984a
Revises:
Create Date: 2026-05-02 09:52:13.060251
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c92d68dd984a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "developer",
                "analyst",
                "viewer",
                name="userrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_created_by"),
        "organizations",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.create_table(
        "projects",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "key", name="uq_project_key"),
    )
    op.create_index(op.f("ix_projects_key"), "projects", ["key"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(
        op.f("ix_projects_organization_id"),
        "projects",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "anomalies",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="anomalyseverity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "resolved", name="anomalystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("signal", sa.String(length=180), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anomalies_project_id"), "anomalies", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_anomalies_severity"), "anomalies", ["severity"], unique=False
    )
    op.create_index(op.f("ix_anomalies_signal"), "anomalies", ["signal"], unique=False)
    op.create_index(op.f("ix_anomalies_status"), "anomalies", ["status"], unique=False)
    op.create_index(op.f("ix_anomalies_title"), "anomalies", ["title"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("requests_per_minute", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "revoked", name="apikeystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(
        op.f("ix_api_keys_project_id"), "api_keys", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_api_keys_status"), "api_keys", ["status"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=True),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"),
        "audit_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_project_id"), "audit_logs", ["project_id"], unique=False
    )
    op.create_table(
        "event_aggregates",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("metric_name", sa.String(length=180), nullable=False),
        sa.Column("grain", sa.String(length=40), nullable=False),
        sa.Column("bucket", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_aggregates_bucket"), "event_aggregates", ["bucket"], unique=False
    )
    op.create_index(
        op.f("ix_event_aggregates_metric_name"),
        "event_aggregates",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_aggregates_project_id"),
        "event_aggregates",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "event_schemas",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("event_name", sa.String(length=180), nullable=False),
        sa.Column("required_properties", sa.JSON(), nullable=False),
        sa.Column("optional_properties", sa.JSON(), nullable=False),
        sa.Column("property_types", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_schemas_event_name"),
        "event_schemas",
        ["event_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_schemas_project_id"),
        "event_schemas",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "funnels",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_funnels_name"), "funnels", ["name"], unique=False)
    op.create_index(
        op.f("ix_funnels_project_id"), "funnels", ["project_id"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "developer",
                "analyst",
                "viewer",
                name="projectrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_member_user"),
    )
    op.create_index(
        op.f("ix_project_members_project_id"),
        "project_members",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_members_role"), "project_members", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_project_members_user_id"), "project_members", ["user_id"], unique=False
    )
    op.create_table(
        "raw_events",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("event_name", sa.String(length=180), nullable=False),
        sa.Column("user_id", sa.String(length=180), nullable=True),
        sa.Column("anonymous_id", sa.String(length=180), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column(
            "ingestion_status",
            sa.Enum(
                "accepted",
                "rejected",
                "processed",
                "failed",
                name="ingestionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("validation_errors", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_events_anonymous_id"), "raw_events", ["anonymous_id"], unique=False
    )
    op.create_index(
        op.f("ix_raw_events_event_name"), "raw_events", ["event_name"], unique=False
    )
    op.create_index(
        op.f("ix_raw_events_ingestion_status"),
        "raw_events",
        ["ingestion_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_events_project_id"), "raw_events", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_raw_events_timestamp"), "raw_events", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_raw_events_user_id"), "raw_events", ["user_id"], unique=False
    )
    op.create_table(
        "pipeline_logs",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("raw_event_id", sa.String(length=36), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "info", "warning", "error", name="pipelineloglevel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("event_name", sa.String(length=180), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["raw_event_id"], ["raw_events.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_logs_event_name"),
        "pipeline_logs",
        ["event_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_logs_level"), "pipeline_logs", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_logs_project_id"),
        "pipeline_logs",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_logs_raw_event_id"),
        "pipeline_logs",
        ["raw_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_logs_raw_event_id"), table_name="pipeline_logs")
    op.drop_index(op.f("ix_pipeline_logs_project_id"), table_name="pipeline_logs")
    op.drop_index(op.f("ix_pipeline_logs_level"), table_name="pipeline_logs")
    op.drop_index(op.f("ix_pipeline_logs_event_name"), table_name="pipeline_logs")
    op.drop_table("pipeline_logs")
    op.drop_index(op.f("ix_raw_events_user_id"), table_name="raw_events")
    op.drop_index(op.f("ix_raw_events_timestamp"), table_name="raw_events")
    op.drop_index(op.f("ix_raw_events_project_id"), table_name="raw_events")
    op.drop_index(op.f("ix_raw_events_ingestion_status"), table_name="raw_events")
    op.drop_index(op.f("ix_raw_events_event_name"), table_name="raw_events")
    op.drop_index(op.f("ix_raw_events_anonymous_id"), table_name="raw_events")
    op.drop_table("raw_events")
    op.drop_index(op.f("ix_project_members_user_id"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_role"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_project_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_funnels_project_id"), table_name="funnels")
    op.drop_index(op.f("ix_funnels_name"), table_name="funnels")
    op.drop_table("funnels")
    op.drop_index(op.f("ix_event_schemas_project_id"), table_name="event_schemas")
    op.drop_index(op.f("ix_event_schemas_event_name"), table_name="event_schemas")
    op.drop_table("event_schemas")
    op.drop_index(op.f("ix_event_aggregates_project_id"), table_name="event_aggregates")
    op.drop_index(
        op.f("ix_event_aggregates_metric_name"), table_name="event_aggregates"
    )
    op.drop_index(op.f("ix_event_aggregates_bucket"), table_name="event_aggregates")
    op.drop_table("event_aggregates")
    op.drop_index(op.f("ix_audit_logs_project_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_status"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_project_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_anomalies_title"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_status"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_signal"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_severity"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_project_id"), table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_key"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_created_by"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
